### ISSUE TITLE
Issue while setting Path

### ISSUE THREAD

**Issue by vardans6** [yukiarrr/ios-build-action#20]
![image](https://user-images.githubusercontent.com/62853122/93847094-9a8d5f80-fcc3-11ea-925c-274546e09c54.png)
![image](https://user-images.githubusercontent.com/62853122/93847113-a9741200-fcc3-11ea-87cd-21029589a3bd.png)

**Comment by vardans6** [comment]
Please help

**Comment by vardans6** [comment]
@yukiarrr

**Comment by yukiarrr** [comment]
@vardans6 Thanks for creating the Issue!
I have one question.
What are you doing before using ios-build-action?
I'd like to see your yaml.

**Comment by vardans6** [comment]
name: iOS-workflow 

on:
  push:
    branches: [ master ]
  #pull_request:
   #  branches: [ master ]

jobs:
  build:
    name:  Build and Test using iPhone simulator
    runs-on: macos-latest

    steps:
      - uses: yukiarrr/ios-build-action@v1.1.1
        with:
          project-path: Yobored.xcodeproj
          p12-base64: ${{ secrets.P12_BASE64 }}
          mobileprovision-base64: ${{ secrets.MOBILEPROVISION_BASE64 }}
          code-signing-identity: ${{ secrets.CODE_SIGNING_IDENTITY }}
          team-id: ${{ secrets.TEAM_ID }}
          #workspace-path: Yobored.xcworkspace
          export-method: development
          configuration: Debug
          certificate-password: ${{ secrets.PASS }}

**Comment by yukiarrr** [comment]
@vardans6 Thanks!
Do you use `actions/checkout@v2`?
To build the repository, you need to do checkout first.

```yaml
- name: Checkout
  uses: actions/checkout@v2
```

**Comment by vardans6** [comment]
@yukiarrr    Sir Problem is, I have to install 3 provisioning profiles, how can I do this?

**Comment by yukiarrr** [comment]
@vardans6 
Since you're getting an error with `Path is invalid`, I'm thinking of the following as causes.

- Because you haven't done checkout yet, `xcodeproj` does not exist
- Because you changed the current directory, the relative path to `Yobored.xcodeproj` has changed

Do you know anything about it?

**Comment by vardans6** [comment]
@ Sir that issue has been resolved.. thanks for that added checkout and its got path..
  How to give multiple provisioning profiles to install?

**Comment by vardans6** [comment]
@yukiarrr 

![image](https://user-images.githubusercontent.com/62853122/93974946-3e464080-fd94-11ea-9788-858121ac887b.png)

**Comment by yukiarrr** [comment]
@vardans6 
With [disable-targets](https://github.com/yukiarrr/ios-build-action#disable-targets), you can specify targets that not use automatic code signing and instead use provisioning profile specified in `Inputs`.
So I think you would be good to use `ios-build-action` for each provisioning profile.

**Comment by vardans6** [comment]
> @vardans6
> With [disable-targets](https://github.com/yukiarrr/ios-build-action#disable-targets), you can specify targets that not use automatic code signing and instead use provisioning profile specified in `Inputs`.
> So I think you would be good to use `ios-build-action` for each provisioning profile.

@yukiarrr Sir invited you collaborate in project please update, i am not understanding how to do that

**Comment by yukiarrr** [comment]
OK!
I'll check back in a few days' time.

**Comment by vardans6** [comment]
Sure

**Comment by yukiarrr** [comment]
> With disable-targets, you can specify targets that not use automatic code signing and instead use provisioning profile specified in Inputs.
So I think you would be good to use ios-build-action for each provisioning profile.

I have found that the above method cannot be built.
So I pushed a new branch that added support for multiple profiles.

```yaml
- uses: yukiarrr/ios-build-action@support-multi-profiles
  with:
    ...
    multi-mobileprovision-base64: |
      {
        "${{ secrets.MOBILEPROVISION_BASE64 }}": ["Yobored"],
        "${{ secrets.BASE64_MOBILEPROVISION_CHATNOTIFICATIONS }}": ["ChatNotificationExtension"],
        "${{ secrets.BASE64_MOBILEPROVISION_SHARE }}": ["ShareToYobored"],
      }
    ...
```

Note that You can verify this above, but it's only temporary, so when branch of support-multi-profiles is removed, it results in an error.
@vardans6 Did the above succeed?

**Comment by vardans6** [comment]
> > With disable-targets, you can specify targets that not use automatic code signing and instead use provisioning profile specified in Inputs.
> > So I think you would be good to use ios-build-action for each provisioning profile.
> 
> I have found that the above method cannot be built.
> So I pushed a new branch that added support for multiple profiles.
> 
> ```yaml
> - uses: yukiarrr/ios-build-action@support-multi-profiles
>   with:
>     ...
>     multi-mobileprovision-base64: |
>       {
>         "${{ secrets.MOBILEPROVISION_BASE64 }}": ["Yobored"],
>         "${{ secrets.BASE64_MOBILEPROVISION_CHATNOTIFICATIONS }}": ["ChatNotificationExtension"],
>         "${{ secrets.BASE64_MOBILEPROVISION_SHARE }}": ["ShareToYobored"],
>       }
>     ...
> ```
> 
> Note that You can verify this above, but it's only temporary, so when branch of support-multi-profiles is removed, it results in an error.
> @vardans6 Did the above succeed?

@yukiarrr  no that not worked, moved with azure devops pipeline

**Comment by yukiarrr** [comment]
OK, thanks for reporting!
And multiple profiles are now supported in v1.3.0.
https://github.com/yukiarrr/ios-build-action/pull/29

```yaml
- uses: yukiarrr/ios-build-action@v1.3.0
  with:
    ...
    mobileprovision-base64: |
      ${{ secrets.MY_MOBILEPROVISION_BASE64 }}
      ${{ secrets.YOUR_MOBILEPROVISION_BASE64 }}
    # Need to use export-options to specify the provisioning profile to use for each executable in your app
    export-options: "path/to/exportOptions.plist"
    ...
```

**Comment by vardans6** [comment]
> OK, thanks for reporting!
> And multiple profiles are now supported in v1.3.0.
> #29
> 
> ```yaml
> - uses: yukiarrr/ios-build-action@v1.3.0
>   with:
>     ...
>     mobileprovision-base64: |
>       ${{ secrets.MY_MOBILEPROVISION_BASE64 }}
>       ${{ secrets.YOUR_MOBILEPROVISION_BASE64 }}
>     # Need to use export-options to specify the provisioning profile to use for each executable in your app
>     export-options: "path/to/exportOptions.plist"
>     ...
> ```

@yukiarrr  thanks sir, will surely try and report you
