### ISSUE TITLE
How to get code signing working for ios build action?

### ISSUE THREAD

**Issue by L4ZZA** [yukiarrr/ios-build-action#50]
Could anyone tell us how to get all these information and how to set them up so that the build actually works?
How are you expected to put those info in the secrets if the p12 key is a binary file? 

```
# p12-base64: ${{ secrets.P12_BASE64 }}
# p12-key-base64: ${{ secrets.P12_KEY_BASE64 }}
# p12-cer-base64: ${{ secrets.P12_CER_BASE64 }}
# mobileprovision-base64: ${{ secrets.MOBILEPROVISION_BASE64 }}
# code-signing-identity: ${{ secrets.CODE_SIGNING_IDENTITY }}
```

P.S. I have tried to follow these docs but nothing is really helping
- https://docs.microsoft.com/en-us/azure/devops/pipelines/apps/mobile/app-signing?view=azure-devops&tabs=apple-install-during-build#apple
- https://www.appdome.com/no-code-mobile-integration-knowledge-base/creating-an-ios-distribution-certificate-and-p12-file-for-signing-ios-apps/
- https://stackoverflow.com/questions/9418661/how-to-create-p12-certificate-for-ios-distribution
- http://docs.phonegap.com/phonegap-build/signing/ios/

**Comment by yukiarrr** [comment]
If you are using Mac, you can get them with the following command.

```sh
cat ${your_p12_file} | base64 | pbcopy # p12-base64
cat ${your_mobileprovision_file} | base64 | pbcopy # mobileprovision-base64
```

**Comment by L4ZZA** [comment]
I see, I have also found this solution:
`base64 -i certificate.p12 -o certificate_base64.txt`
and then you can copy the text file content into the secret on github
