### ISSUE TITLE
Enable custom entitlements

### ISSUE THREAD

**Issue by proohit** [yukiarrr/ios-build-action#91]
Hi,

thanks for your awesome action. I'm trying to build an app using custom Configurations with entitlements in separate files. However, there is no option in the action to configure custom entitlement files. Fastlane supports entitlement files using the `entitlements_file_path` option in `update_code_signing_settings` (see http://docs.fastlane.tools/actions/update_code_signing_settings/#parameters).

I don't know if this is the exact attribute to control, but local builds in xCode work with no problems. The custom entitlement files are configured in xcode. How can I pass custom entitlements files to the action in order to be picked up in fastlane?

**Comment by dasheck0** [comment]
As far as I can tell this action does not support custom entitlement files. See https://github.com/yukiarrr/ios-build-action/blob/3d8ff63d40bce5dfd0ff8d1dda6ce543bf4c605a/fastlane/Fastfile#L63 There should be an option to provide custom parameters to the `update_code_signing_settings` function. 

Another option is to run resign afterwards (see https://github.com/fastlane/fastlane/issues/17727), but this seems like a hacky workaround.

@yukiarrr Is this repo still maintained?

**Comment by dasheck0** [comment]
@yukiarrr Did it myself. See #92. Hope you merge it soon as it is a blocker for us. Thanks!

**Comment by dungi** [comment]
@dasheck0 I guess this feature broke my CI. Cause I have more than 1 entitlement file in my project (Main App, Widgets, WatchApp) the default value ("") would set all paths for the ".envirionment"-File to "", which is currently not what I need. If I set multiple paths, every target gets all 3 entitlements paths set. I need to revert to version 1.5.0
